export const Channels = {
  sessionList: 'session:list',
  sessionCreate: 'session:create',
  sessionWrite: 'session:write',
  sessionResize: 'session:resize',
  sessionStop: 'session:stop',
  sessionHistory: 'session:history',
  sessionData: 'session:data',
  sessionExit: 'session:exit',
  entryList: 'entry:list',
  entryAdd: 'entry:add',
  /** 渲染层唯一的条目写入口，逐字段校验并挡住运行中改身份，PRD §4.6 */
  entryEdit: 'entry:edit',
  entryRemove: 'entry:remove',
  entryReorder: 'entry:reorder',
  entryDetect: 'entry:detect',
  entryPrecheck: 'entry:precheck',
  entryStart: 'entry:start',
  entryStop: 'entry:stop',
  entryRestart: 'entry:restart',
  entryInstall: 'entry:install',
  entryRunScript: 'entry:runScript',
  entryDiagnose: 'entry:diagnose',
  entryOutputDir: 'entry:outputDir',
  entryOpenPackageJson: 'entry:openPackageJson',
  entryRuntimes: 'entry:runtimes',
  entryChanged: 'entry:changed',
  /** 日志中心，PRD §4.8。筛选在主进程做，渲染层只拿要显示的那一屏 */
  logQuery: 'log:query',
  logClear: 'log:clear',
  entryRuntimeChanged: 'entry:runtimeChanged',
  /** 主进程侧的非致命告警（如端口 5 秒未释放），只进实时动态，不弹窗 */
  entryWarning: 'entry:warning',
  dialogPickDirectory: 'dialog:pickDirectory',
  shellOpenLocalhost: 'shell:openLocalhost',
  shellOpenPath: 'shell:openPath',
  scannerSnapshot: 'scanner:snapshot',
  scannerDiff: 'scanner:diff',
  scannerRefresh: 'scanner:refresh',
  scannerVisibility: 'scanner:visibility',
  scannerIgnore: 'scanner:ignore',
  scannerHideOnce: 'scanner:hideOnce',
  /** 手动提升到「我的服务」或移回后台，PRD §5.2 */
  scannerSetGroup: 'scanner:setGroup',
  scannerWatchedGet: 'scanner:watchedGet',
  scannerWatchedSet: 'scanner:watchedSet',
  settingsGet: 'settings:get',
  settingsPatch: 'settings:patch',
  settingsChanged: 'settings:changed',
  themeGet: 'theme:get',
  themeSet: 'theme:set',
  themeChanged: 'theme:changed',
  windowIsMaximized: 'window:isMaximized',
  windowMaximizeChanged: 'window:maximizeChanged'
} as const

export type Channel = (typeof Channels)[keyof typeof Channels]
